### ISSUE TITLE
Mutations don't work with an enum

### ISSUE THREAD

**Issue by HeinPauwelyn** [code4me/4me-sdk-graphql-dotnet#1]
I want to create a request on out 4me tenant and setting the category on `RequestCategory.Incident` when executing the mutation, I've got next error and stack trace:

```
Sdk4me.GraphQL.Sdk4meException: Variable $input of type RequestCreateInput! was provided invalid value for category (Invalid value for RequestCategory: '4'. Please supply one of: 'incident', 'rfc', 'rfi', 'reservation', 'order', 'fulfillment', 'complaint', 'compliment', 'other')
   at Sdk4me.GraphQL.Sdk4meClient.<SendHttpRequest>d__36.MoveNext()
   at Sdk4me.GraphQL.Sdk4meClient.<Mutation>d__31`2.MoveNext()
   at Sdk4me.GraphQL.Sdk4meClient.<Mutation>d__30`2.MoveNext()
   at Sdk4me.GraphQL.Sdk4meClientMutationExtension.<Mutation>d__128.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\**\ConsoleApp1\Program.cs:line 17
```

Below a minimal but complete piece of code to reproduce the error:

```csharp
using Sdk4me.GraphQL;

Sdk4meClient sdk4MeClient = new(
    new AuthenticationToken ("<enter-pat-here>"),
    "<enter-account-name-here>",
    EnvironmentType.Quality,
    EnvironmentRegion.EU
);

RequestCreateInput requestCreateInput = new RequestCreateInput()
{
    Subject = "Test",
    Note = "# Something to test",
    Category = RequestCategory.Incident
};

RequestCreatePayload requestCreatePayload = await sdk4MeClient.Mutation(requestCreateInput);

Console.WriteLine(requestCreatePayload.Request?.RequestId);
Console.Write("Press enter key to exit ");
Console.Read();
```

* **.NET version:** .NET 6.0
* **Package version:** 1.0.2

**Comment by klaasvandeweerdt** [comment]
@HeinPauwelyn
Thanks for the reproduction code, the issue is resolved.
Version 1.0.3 is available on GitHub and NuGet.

**Comment by HeinPauwelyn** [comment]
@klaasvandeweerdt Thanks for the quick response! It works great now 👍🏻.
